stuff = input('Digite o que quiser agora! ')
print('O tipo primitivo è {}'.format(type(stuff)))
print('É número? {}'.format(stuff.isnumeric()))
print('É letra? {}'.format(stuff.isalpha()))
print('É alphanumérico? {}'.format(stuff.isalnum()))
print('É número? {}'.format(stuff.isascii()))
print('É digito? {}'.format(stuff.isdigit()))
print('É decimal? {}'.format(stuff.isdecimal()))
print('É número? {}'.format(stuff.isidentifier()))
print('É imprimível? {}'.format(stuff.isprintable()))
print('É um espaço? {}'.format(stuff.isspace()))
print('É número? {}'.format(stuff.istitle()))
print('Está capitalizado? {}'.format(stuff.isupper()))
